// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-My0vGMBoCUVZtqWCbW71kKlzjMZ57w4',
    appId: '1:414811981759:web:e2b8fa6e5eabb755cb430a',
    messagingSenderId: '414811981759',
    projectId: 'chatapp-c34e8',
    authDomain: 'chatapp-c34e8.firebaseapp.com',
    storageBucket: 'chatapp-c34e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQzBUXo2J590XZA9LLQ_KTDuNCetJV7M',
    appId: '1:414811981759:android:a645d7ce92f6ca1dcb430a',
    messagingSenderId: '414811981759',
    projectId: 'chatapp-c34e8',
    storageBucket: 'chatapp-c34e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YTNnF2WDqZf1aFHryHKi-bFbHN_KPkI',
    appId: '1:414811981759:ios:28235c2bd2defa63cb430a',
    messagingSenderId: '414811981759',
    projectId: 'chatapp-c34e8',
    storageBucket: 'chatapp-c34e8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2YTNnF2WDqZf1aFHryHKi-bFbHN_KPkI',
    appId: '1:414811981759:ios:81883d02ae999a0ccb430a',
    messagingSenderId: '414811981759',
    projectId: 'chatapp-c34e8',
    storageBucket: 'chatapp-c34e8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
